baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'

theme = "hugo-bootstrap"

disableHugoGeneratorInject = true

enableRobotsTXT = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
